runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app --timeout 32000000

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10